[package]
name = "ecbt"
version = "0.1.0"
edition = "2021"
description = "High performance cryptocurrency trading API with support for user defined networking."
repository = "https://github.com/nash-io/openlimits"
keywords = ["cryptocurrency", "exchange", "openlimits", "api"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
thiserror = "1"
lazy_static = "1.4"
async-trait = "0.1"
rust_decimal = "1.14.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_qs = "0.8"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["compat"] }
toml = "0.5"
ring = "0.16"
hex = "0.4"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }

[workspace]
